### ISSUE TITLE
Plugin is no longer cross-published

### ISSUE THREAD

**Issue by Philippus** [mefellows/sbt-dotenv#105]
Hi, I noticed we are now only targeting sbt 1.0+ versions when publishing. I think that's fine, it's time to move on anyway. People still on sbt 0.13.x can use an older version. But that does mean we can clean up the build a bit.

**Comment by mefellows** [comment]
That's probably my naivety around that process - if it should cross-publish we should do that. But i'll take your guidance!

**Comment by Philippus** [comment]
https://github.com/mefellows/sbt-dotenv/pull/126 targets only sbt version 1.3.9 and up.
