### ISSUE TITLE
Support for SBT 1.0.0 

### ISSUE THREAD

**Issue by darrenagibson** [mefellows/sbt-dotenv#11]
Doing a quick glance at the code/build, it doesn't look like much has to change.  The project compiles with SBT version 1.0.0 just fine it seems.  

So my question is... do you want to Cross Build the SBT versions or would a PR that just straight up builds against 1.0.0 only be acceptable?

**Comment by mefellows** [comment]
I'm happy with either. I've been out of the Scala game for a while unfortunately, so not sure what the current usage/standards are. It looks like SBT 1.0 requires Scala 2+, is that right?

If so, backwards compatibility with 1.x would be great.

**Comment by mefellows** [comment]
Closed by #12

**Comment by zarthross** [comment]
The merge build failed.  Looks like I made some incorrect assumptions about how your build was configured.  Do you know what the 'secure' env vars was in the travis.yml?

In either case, the reason is failing is because you need to setup 2 env vars in Travis
`BINTRAY_USER` and `BINTRAY_PASS`.

`BINTRAY_PASS` shoud be the bintray API key.

**Comment by mefellows** [comment]
Yep I started looking into it and then, you know, life got in the way!

 @Philippus has kindly offered to help me get this fixed and help maintain his (I'm happy to offer to you also given your recent contributions).

In the meanwhile, I'll see about obtaining new creds and adding to the `.travis.yml` file.

**Comment by mefellows** [comment]
Cool, I've reinstated the old script that setup the Bintray credentials and we now have a [green build](https://travis-ci.org/mefellows/sbt-dotenv/jobs/271295804#L643) and [latest release](https://bintray.com/mefellows/sbt-plugins/sbt-dotenv/1.2.58)

**Comment by Philippus** [comment]
cool! I've pushed a tag, so now it's also available under https://github.com/mefellows/sbt-dotenv/releases
