### ISSUE TITLE
Allow newlines in .env files

### ISSUE THREAD

**Issue by joostverdoorn** [mefellows/sbt-dotenv#22]
Hi there! Coming from JavaScript, Ruby and Python land, I was pleasently surprised to find the dotenv pattern also supported in sbt through your plugin. 

I do have one request: most other dotenv implementations allow newlines in the values specified in the .env files, usually through the use of quotes surrounding the entire value. This is very helpful when defining e.g. PEM certificates in the .env file, as follows:

```
KAFKA_CA="-----BEGIN CERTIFICATE-----
MIIDfzCCAmegAwIBAgIBADANBgkqhkiG9w0BAQsFADAyMTAwLgYDVQQDDCdjYS0z
MjFiNzkzNS0wZWQ3LTRiY2ItYTc3Ni1hMzVmZWUwOWZiY2UwHhcNMTcwOTA1MTI1
...
bT+oHoJIz5UhTpnXKnLubG1SGnsynGCNJuxXrbtq+y7nuNgp1tT+sUAZn5MdaKnI
2nt0TqLiyWu7rKOuSYUnu103CZlNkZzv+i5/4tNr9Wym6Ic=
-----END CERTIFICATE-----
"
```

I'd much appreciate it if such behavior can be added to your plugin. For now, I've worked around this by base64 encoding the certificates for local development, but this obviously is suboptimal.

Cheers!

**Comment by mefellows** [comment]
Thanks for the kind words, I'm completely open to this so long as we can still provide backwards compatibility.

I won't have time to look at this for a little while, but will keep it on the backlog and hope it gets picked up sooner.
