### ISSUE TITLE
Environment variables do not persist to child processes (documentation request)

### ISSUE THREAD

**Issue by danielkza** [mefellows/sbt-dotenv#3]
This project has been quite useful to me in my testing (thanks!), but I've found to my surprise that no actual environment variables are being set, the internal information from the JVM is just being 'fooled'. I understand that this is a limitation of the Java class libraries, but it would be quite helpful to document this.

I believe it should also be possible to set actual env. vars using FFI calls, like [these examples](http://blog.quirk.es/2009/11/setting-environment-variables-in-java.html). On known platforms (POSIX and Windows) the native methods would be used, and the existing method would be a fall back.

**Comment by mefellows** [comment]
Great to hear it's of value - and thanks for helping make it more so! OK, I'm reviewing the PR as we speak. Your suggestion sounds reasonable; although the original intention was to avoid polluting the 'real' environment and just pass into the JVM, the limitations noted make that difficult to do.

Modifying the 'real' host OS is probably the way to go. I'm going to change this to a defect as that is really what it is, and once we resolve your PR (#4) we can close.
