### ISSUE TITLE
Changing the .env filename

### ISSUE THREAD

**Issue by mfogel** [mefellows/sbt-dotenv#33]
Hi, thanks for your work on sbt-dotenv. Super helpful.

When I try to change the name of the `.env` file to something else in my build.sbt, sbt throws an error. I'm running sbt version 1.1.6

I've added verbatim the line

```
envFileName in ThisBuild := "dev.env"
```

To my `build.sbt`. The error that is thrown:

```sh
$ sbt run
[info] Loading settings from plugins.sbt ...
[info] Loading project definition from /Users/mfogel/aa/scala-stuff/project
/Users/mfogel/aa/scala-stuff/build.sbt:60: error: not found: value envFileName
envFileName in ThisBuild := "dev.env"
^
[error] Type error in expression
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? [info] Loading settings from plugins.sbt ...
```

The plugin otherwise seems to work well. Am I missing something doing something stupid here? I'm somewhat new to the whole scala world still... Thanks.

**Comment by Philippus** [comment]
which version of `sbt-dotenv` are you using? Newest version is `2.0.117`

**Comment by mfogel** [comment]
That was the problem. I was using version `1.2.88`, as mentioned in the readme. Works like a charm with `2.0.117`. Thanks.

Might be worthwhile mentioning something in the README about travis auto-generating releases, and a link to bintray or whatnot where the latest release is listed.

**Comment by Philippus** [comment]
:+1: I've updated the version number in the README.
