### ISSUE TITLE
Using envFileName in IntegrationTests

### ISSUE THREAD

**Issue by erwan** [mefellows/sbt-dotenv#44]
I'm not sure if it is something I'm doing wrong, but I'm unable to override the envfile for integration tests.

I have this:
```
envFileName in Test := ".env.test"

envFileName in IntegrationTest := ".env.it"
```

When I run `sbt test` the correct env file is used, however when I run `sbt it:test` the default `.env` file is used.

Is it an issue in the plugin or something I'm doing wrong?

**Comment by Philippus** [comment]
I think we would need the feature that is proposed in https://github.com/mefellows/sbt-dotenv/pull/42 ? @slavaschmidt is it possible to make this work for integration tests as well?

**Comment by slavaschmidt** [comment]
@Philippus Should work out of the box, I'll extend the scripted test to make sure it does.

**Comment by Philippus** [comment]
@erwan can you try version `2.1.146` and see if it does what you want? To see the steps that are involved check out this [test](https://github.com/mefellows/sbt-dotenv/tree/master/src/sbt-test/sbt-dotenv/check-load-on-demand-dot-env).

**Comment by Philippus** [comment]
@erwan can we close this issue?

**Comment by erwan** [comment]
Yes, sorry for the late response - it works now!

**Comment by Philippus** [comment]
Thank you, good to know!
