### ISSUE TITLE
Environment variables are not loaded early enough to be used on SBT settings

### ISSUE THREAD

**Issue by danielkza** [mefellows/sbt-dotenv#5]
It seems environment variables are only loaded after all the project settings have been evaluated. I wanted to derive some settings from the env vars and was surprised it wasn't working. I don't know how exactly how to fix it since SBT doesn't seem to provide any hooks earlier than `onLoad`, which is already too late.

**Comment by mefellows** [comment]
Interesting idea. The original intention was for running app code to be setup but I suppose that could be handy as well. I'll take a look at the SBT API throughout the week to see if I can get it lower in the execution stack.

**Comment by danielkza** [comment]
I actually tried lots of things myself and I haven't found any elegant alternatives. I settled with creating a command in my build settings that will set things up and reload the project. It's enough for me since my use case was running database migrations manually in Heroku, grabbing the credentials from the environment.

**Comment by mefellows** [comment]
OK great that you've found an alternative. If you're happy then I'll close
off this issue. If you don't mind, for others who stumble across this
issue, could you post a gist or something showing the solution / workaround
that you've come up with?

On Mon, Jan 5, 2015 at 2:29 AM, Daniel Miranda <notifications@github.com>
wrote:

> I actually tried lots of things myself and I haven't found any elegant
> alternatives. I settled with creating a command in my build settings that
> will set things up and reload the project. It's enough for me since my use
> case was running database migrations manually in Heroku, grabbing the
> credentials from the environment.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mefellows/sbt-dotenv/issues/5#issuecomment-68636603>.
>



-- 
Matt Fellows
- http://www.onegeek.com.au/

**Comment by danielkza** [comment]
Sure, but it's not very elegant. Since I haven't found a good way to change settings from commands/hooks, I resorted to simply running a `set` command manually and letting SBT reload afterwards. What do you think of having a setting like `reloadOnEnvironmentChange`, defaulting to false, that would make the plugin trigger a reload automatically right after the environment is loaded?

**Comment by mefellows** [comment]
Thanks @danielkza, I'll close this one off and hopefully any passers' by can benefit from your answer.

**Comment by nmccready** [comment]
Wait scratch that it only worked due to calling `reload` as @danielkza stated. This really should be considered a bug. The envs should be available as early as possible.

**Comment by outkaj** [comment]
I ran into issues loading the variables even after calling `reload` manually and enabling the plugin. The context is a Play project so I would prefer not to have to declare configuration settings for environment variables in `build.sbt` as above - ideally, I should just be able to reference them once in the `application.conf`. (Unless this plugin isn't compatible with Play?) 
I agree this should be considered a bug and believe this should be re-opened.

**Comment by outkaj** [comment]
@mefellows sorry to be annoying, but could you let me know if you are planning on resolving this at some point / re-opening? (I ask again because it's relevant/time-sensitive as I'm trying to use this plugin for local development for a development team and need to assess if it's the best option for us). Thanks for your help and work.

**Comment by mefellows** [comment]
I personally haven't written any Scala for a few years now, so am very much out of touch with the current state of play (pun not intended, but also true) around SBT tooling and frameworks.

I'm absolutely open for somebody to submit a patch/change to enable this behaviour, but I'm sorry to say that I simply don't have time to dig into this at the moment.

**Comment by outkaj** [comment]
Totally understood, thanks for clarifying!

**Comment by outkaj** [comment]
@PaperPlaneSoftware I didn't, I think I just ended up not trying to do this with SBT. And I'm now unfortunately in the position where I also can say "I personally haven't written any Scala for a few years now, so am very much out of touch with the current state of play (pun not intended, but also true) around SBT tooling and frameworks."
